title: Dov Yellin
#logo: /assets/img/IMG_0771.JPG
#description: Data Analyst Portfolio
#show_downloads: false
#theme: jekyll-theme-time-machine
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
